export {
  CommsPliantEditor,
  type CommsPliantEditorProps,
  type VariableDefinition,
  type VariablePreviewValues,
  type AiAssistantAction,
  type AiAssistantBlockContext,
  type AiAssistantContext,
  type AiAssistantRequest,
  type AiAssistantSuggestion,
  type AiAssistantSuggestionAction,
} from './components/DocumentEditor/DocumentEditor'
export {
  DOCUMENT_SCHEMA_VERSION,
  createDocument,
  isDocumentBackgroundColour,
  isPageNumbering,
  isLetterDocument,
  type BackgroundImageFit,
  type BackgroundImagePosition,
  type CreateDocumentOptions,
  type DocumentBackgroundColour,
  type DocumentBackgroundImage,
  type DocumentData,
  type DocumentLayout,
  type EditorComponents,
  type FluidDocumentLayout,
  type LetterDocument,
  type PageMargins,
  type PageNumbering,
  type PagedDocumentLayout,
  type RichTextDocument,
  type RichTextMark,
  type RichTextNode,
  type RichTextValue,
  type SpacerSize,
  type TableAlignment,
  type TableData,
  type TableRow,
} from './document/document'
